Re-enable Bison parser and fast unparser (#42)
* Makefile: generate bison parser too

* kmich: add interpret command for fast-path parsing/unparsing

* kmich: correct argument list

* kmich: correct way to invoke llvm-krun

* kmich: enable debug and working with compat backends

* Makefile: use interpret command for speeeeedddd

* run-with-tezos.sh: keep going on single test failure

* run-with-tezos, fix-address, run-tezos: formatting and nice messages

* run-with-tezos.sh: remove use of status

* Jenkinsfile: lower timeout on test stage

* kmich: typo

* Jenkinsfile: no need for kserver

* Makefile: capitalize HOOK_NAMESPACES

diff --git a/kmich b/kmich
--- a/kmich
+++ b/kmich
@@ -35,7 +35,7 @@ run_krun() {
 run_kast() {
     local output_mode
 
-    output_mode="$1"
+    output_mode="$1" ; shift
     kast --directory "$backend_dir" "$run_file" --output "$output_mode" "$@"
 }
 
@@ -47,6 +47,21 @@ run_prove() {
     kprove --directory "$backend_dir" "$run_file" --def-module "$def_module" "$@"
 }
 
+run_interpret() {
+    local in_kore out_kore
+
+    in_kore=$(mktemp $kompiled_dir/in_kore.XXXXXX)
+    out_kore=$(mktemp $kompiled_dir/out_kore.XXXXXX)
+    if $debug; then
+        notif "Input Kore: $in_kore"
+        notif "Output Kore: $out_kore"
+        trap "rm -rf $in_kore $out_kore" INT TERM EXIT
+    fi
+
+    cat "$run_file" | $kompiled_dir/parser_PGM > $in_kore
+    llvm-krun --directory "$kompiled_dir" -c PGM $in_kore Pgm korefile --pretty-print "${llvm_krun_args[@]}" "$@"
+}
+
 # Main
 # ----
 
@@ -54,22 +69,25 @@ run_command="$1" ; shift
 
 if [[ "$run_command" == 'help' ]] || [[ "$run_command" == '--help' ]] ; then
     echo "
-        usage: $0 run   [--backend (llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)] <pgm>  <K arg>*
-               $0 kast  [--backend (llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)] <pgm>  <output format> <K arg>*
-               $0 prove [--backend (prove|symbolic)]                                                      <spec> <def_module>    <K arg>*
+        usage: $0 run       [--backend (llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)] <pgm>  <K arg>*
+               $0 kast      [--backend (llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)] <pgm>  <output format> <K arg>*
+               $0 prove     [--backend (prove|symbolic)]                                                               <spec> <def_module>    <K arg>*
+               $0 interpret [--backend (llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)] <pgm>  <LLVM KRun arg>*
 
                $0 [help|--help|version|--version]
 
-           $0 run       : Run a single EVM program
-           $0 kast      : Parse an EVM program and output it in a supported format
-           $0 prove     : Run an EVM K proof
+           $0 run       : Run a single Michelson program.
+           $0 kast      : Parse a Michelson program and output it in a supported format.
+           $0 prove     : Run a Michelson K proof.
+           $0 interpret : Run a single Michelson program using the fast bison parser.
 
            $0 help    : Display this help message.
-           $0 version : Display the versions of KMich, K, Kore, and Z3 in use.
+           $0 version : Display the versions of KMichelson, K, Kore, and Z3 in use.
 
            Note: <pgm> is a path to a file containing an EVM program/test.
                  <spec> is a K specification to be proved.
                  <K arg> is an argument you want to pass to K.
+                 <LLVM KRun arg> are arguments to pass to llvm-krun.
                  <output format> is the format for Kast to output the term in.
                  <def_module> is the module to take as axioms when doing verification.
     "
@@ -102,6 +120,8 @@ while [[ $# -gt 0 ]]; do
     esac
 done
 backend_dir="${backend_dir:-$defn_dir/$backend}"
+kompiled_dir=$(find $backend_dir -name '*-kompiled')
+[[ -d "$kompiled_dir" ]] || fatal "Could not find single *-kompiled directory in $backend_dir"
 
 # get the run file
 run_file="$1" ; shift
@@ -113,11 +133,18 @@ if [[ "$run_file" == '-' ]]; then
 fi
 [[ -f "$run_file" ]] || fatal "File does not exist: $run_file"
 
+llvm_krun_args=()
+! $debug \
+    || llvm_krun_args+=(--debug)
+! echo "$backend_dir" | grep -e contract-expander -e extractor -e input-creator -e output-compare &> /dev/null \
+    || llvm_krun_args+=(-c IO '\dv{SortString{}}("on")' String kore)
+
 case "$run_command-$backend" in
 
     # Running
-    run-@(llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)  ) run_krun  "$@" ;;
-    kast-@(llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare) ) run_kast  "$@" ;;
-    prove-@(prove|symbolic)                                                              ) run_prove "$@" ;;
+    run-@(llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)       ) run_krun       "$@" ;;
+    kast-@(llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare)      ) run_kast       "$@" ;;
+    prove-@(prove|symbolic)                                                                   ) run_prove      "$@" ;;
+    interpret-@(llvm|prove|symbolic|contract-expander|extractor|input-creator|output-compare) ) run_interpret  "$@" ;;
     *) $0 help ; fatal "Unknown command on backend: $run_command $backend" ;;
 esac
