Improve `./kmich` test runner (#122)
* kmich: always delete kore files unless using debug mode

* kmich: make symbtest post-process only on krun success

diff --git a/kmich b/kmich
--- a/kmich
+++ b/kmich
@@ -56,6 +56,7 @@ run_interpret() {
     if $debug; then
         notif "Input Kore: $in_kore"
         notif "Output Kore: $out_kore"
+    else
         trap "rm -rf $in_kore $out_kore" INT TERM EXIT
     fi
 
@@ -64,7 +65,12 @@ run_interpret() {
 }
 
 run_symbtest() {
-    run_krun --search-final --output json "$@" | $kmich_dir/lib/michelson-test-check "$kompiled_dir"
+    output=$(run_krun --search-final --output json "$@")
+    if [ $? -ne 0 ]; then
+        echo "$output" >&2
+        fatal "krun encountered an error: skipping post-processing"
+    fi
+    echo "$output" | $kmich_dir/lib/michelson-test-check "$kompiled_dir"
 }
 
 # Main
