Update unit tests to be consistent with upstream (#148)
* Trailing whitespace

* Various updates to the unit tests

* tests: fix operation test syntax

* tests: update cross test runner to extract real addresses

* syntax: update blockchain operation literals

* tests: update/simplify address grep logic

* tests: ensure that address grep failure doesn't kill script

* tests: use contract-expander dir for operation decoding kast cmd

* michelson: update other_contracts syntax

* tests: mark more unit tests as successfully passing

Co-authored-by: Raphaël Cauderlier <raphael.cauderlier@nomadic-labs.com>

diff --git a/lib/tezos-client-unit-test b/lib/tezos-client-unit-test
--- a/lib/tezos-client-unit-test
+++ b/lib/tezos-client-unit-test
@@ -67,11 +67,16 @@ fix_address() {
     export ORIGINATION_SUBS="$TEMP_DIR/origination_subs"
     export ALL_SUBS="$TEMP_DIR/subs"
 
-    if ! grep -o '@Address([^)"]*)' "$test" | sort | uniq > "$FOUND_ADDRESSES"; then
-        touch "$FOUND_ADDRESSES"
-    fi
+    # grep pattern is for tezos contract account address literals
+    # contract account address literals are double-quoted strings with:
+    # 1. the prefix KT1
+    # 2. a suffix of length 33 written with the bitcoin base 58 alphabet, i.e., with "I", "O", "0" and "l" removed.
+    # The entire pipeline should succeed and do nothing if the grep fails
+    touch "$FOUND_ADDRESSES"
+    grep --only-matching --extended-regexp '"KT1[123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz]{33}"' "$test" \
+        | tr -d '"' | sort | uniq > "$FOUND_ADDRESSES" || true
 
-    extract other_contracts true | tr -d '{}' | tr ';' '\n' | sed -E 's/^\s*//;s/\s*$//;s/Elt\s*"([^"]*)"\s*(.*)/\1#\2/;/^\s*$/d' > "$REAL_ADDRESSES_UNSORTED"
+    extract other_contracts true | tr -d '{}' | tr ';' '\n' | sed -E 's/^\s*//;s/\s*$//;s/Contract\s*"([^"]*)"\s*(.*)/\1#\2/;/^\s*$/d' > "$REAL_ADDRESSES_UNSORTED"
 
     export FAKE_SENDER=$(extract sender true)
     if [ ! -z $FAKE_SENDER ] && ! ( grep "$FAKE_SENDER" "$REAL_ADDRESSES_UNSORTED" ); then
